version: '3.5'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/web/Dockerfile
    ports:
      - 3035:80
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: ./compose/local/fast-api/Dockerfile
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    env_file:
      - .env/development
    depends_on:
      - db

  db:
    image: ghcr.io/chroma-core/chroma:0.4.17
    volumes:
      - chroma_db_data:/chroma/chroma/
    ports:
      - 8000:8000

volumes:
  chroma_db_data:
