#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

chromadb_ready() {
python << END
import sys

import chromadb

try:
  chroma_client = chromadb.HttpClient(host='db', port=8000)
except ValueError:
    sys.exit(-1)
sys.exit(0)

END
}
until chromadb_ready; do
  >&2 echo 'Waiting for ChromaDB to become available...'
  sleep 1
done
>&2 echo 'ChromaDB is available'

exec "$@"
